name: Build binaries

on:
  workflow_dispatch:

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: linux
          task: build-binaries-linux
    name: build binaries for ${{ matrix.platform.name }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@int
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          *.golang.org:443
          registry.yarnpkg.com:443
          storage.googleapis.com:443

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        go-version: 1.19.x

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build binaries
      run: make ${{ matrix.platform.task }}
