name: Build binaries ARC k8s modee

on:
  workflow_dispatch:

jobs:
  build-binaries:
    runs-on: arc0
    container: ubuntu
    
    name: build binaries for linux
    steps:

    - run: apt update

    - uses: actions/checkout@main

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@main
      with:
        go-version: 1.19.x

    # - name: Export BRANCH variable
    #   uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build binaries
      run: make build-binaries-linux
